CREATE TABLE "commercial_scenarios" (
  "id" UUID PRIMARY KEY,"componentId" UUID NOT NULL,"scenarioKey" UUID NOT NULL,"name" VARCHAR(160) NOT NULL,"version" INTEGER NOT NULL,"previousVersionId" UUID,"currency" CHAR(3) NOT NULL,"baseDate" DATE NOT NULL,"estimatedValue" DECIMAL(19,4) NOT NULL,"estimatedSource" VARCHAR(500) NOT NULL,"assumptions" JSONB NOT NULL,"items" JSONB NOT NULL,"totalCost" DECIMAL(19,4) NOT NULL,"offeredPrice" DECIMAL(19,4) NOT NULL,"discountPercent" DECIMAL(9,6) NOT NULL,"marginAmount" DECIMAL(19,4) NOT NULL,"marginPercent" DECIMAL(9,6) NOT NULL,"formulaVersion" VARCHAR(40) NOT NULL,"calculationHash" CHAR(64) NOT NULL,"createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdBy" UUID NOT NULL,"correlationId" UUID NOT NULL,
  CONSTRAINT "commercial_scenario_component_fkey" FOREIGN KEY("componentId") REFERENCES "proposal_components"("id") ON DELETE RESTRICT,
  CONSTRAINT "commercial_scenario_previous_fkey" FOREIGN KEY("previousVersionId") REFERENCES "commercial_scenarios"("id") ON DELETE RESTRICT,
  CONSTRAINT "commercial_scenario_unique" UNIQUE("scenarioKey","version"),CONSTRAINT "commercial_scenario_version_positive" CHECK("version">0),CONSTRAINT "commercial_scenario_currency" CHECK("currency"~'^[A-Z]{3}$'),CONSTRAINT "commercial_scenario_values" CHECK("estimatedValue">=0 AND "totalCost">=0 AND "offeredPrice">=0),CONSTRAINT "commercial_scenario_formula" CHECK("formulaVersion"='GSIPRO-CALC-001')
);
CREATE INDEX "commercial_scenario_component_idx" ON "commercial_scenarios"("componentId","createdAt");CREATE INDEX "commercial_scenario_previous_idx" ON "commercial_scenarios"("previousVersionId");CREATE INDEX "commercial_scenario_correlation_idx" ON "commercial_scenarios"("correlationId");
CREATE FUNCTION "validate_commercial_scenario_chain"() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE component_type "ProposalComponentType";latest RECORD;BEGIN SELECT "type" INTO component_type FROM "proposal_components" WHERE "id"=NEW."componentId";IF component_type IS DISTINCT FROM 'COMMERCIAL' THEN RAISE EXCEPTION 'commercial scenario requires commercial component';END IF;SELECT "id","version","componentId" INTO latest FROM "commercial_scenarios" WHERE "scenarioKey"=NEW."scenarioKey" ORDER BY "version" DESC LIMIT 1;IF latest."id" IS NULL THEN IF NEW."version"<>1 OR NEW."previousVersionId" IS NOT NULL THEN RAISE EXCEPTION 'first commercial scenario version must be 1';END IF;ELSIF NEW."version"<>latest."version"+1 OR NEW."previousVersionId"<>latest."id" OR NEW."componentId"<>latest."componentId" THEN RAISE EXCEPTION 'commercial scenario must extend latest version in same component';END IF;RETURN NEW;END $$;
CREATE TRIGGER "commercial_scenario_chain_guard" BEFORE INSERT ON "commercial_scenarios" FOR EACH ROW EXECUTE FUNCTION "validate_commercial_scenario_chain"();
CREATE FUNCTION "reject_commercial_scenario_mutation"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'commercial scenarios are append-only';END $$;CREATE TRIGGER "commercial_scenario_append_only" BEFORE UPDATE OR DELETE ON "commercial_scenarios" FOR EACH ROW EXECUTE FUNCTION "reject_commercial_scenario_mutation"();
