import { createHash, randomUUID } from "node:crypto";
import { getDatabase } from "@/core/database/prisma";
import type { Prisma } from "@/generated/prisma/client";
import type { TechnicalReviewRepository } from "@/modules/proposal-reviews/application/technical-review-service";
import type { TechnicalCommentDraft, TechnicalCommentResolution, TechnicalContentDraft, TechnicalEvidenceLinkDraft, TechnicalReviewDraft } from "@/modules/proposal-reviews/domain/technical-review";

export class TechnicalReviewNotFoundError extends Error { constructor(message="Seção, comentário ou evidência não encontrada."){super(message);this.name="TechnicalReviewNotFoundError"} }
export class TechnicalReviewRuleError extends Error { constructor(message:string){super(message);this.name="TechnicalReviewRuleError"} }

export class PrismaTechnicalReviewRepository implements TechnicalReviewRepository {
  async addContent(sectionId:string,draft:TechnicalContentDraft,actorId:string,correlationId:string){return getDatabase().$transaction(async tx=>{const section=await this.currentSection(tx,sectionId);if(section.responsibleId!==actorId)throw new TechnicalReviewRuleError("Somente o responsável atual pode elaborar o conteúdo da seção.");const previous=await tx.proposalTechnicalContentVersion.findFirst({where:{sectionId},orderBy:{version:"desc"}});const version=(previous?.version??0)+1;const contentHash=createHash("sha256").update(draft.content,"utf8").digest("hex");const created=await tx.proposalTechnicalContentVersion.create({data:{id:randomUUID(),sectionId,version,previousVersionId:previous?.id,content:draft.content,reason:draft.reason,contentHash,createdBy:actorId,correlationId}});if(section.status==="DRAFT"){const updated=await tx.proposalTechnicalSection.update({where:{id:sectionId},data:{status:"IN_PROGRESS",version:{increment:1},updatedBy:actorId}});await tx.proposalTechnicalSectionHistory.create({data:{id:randomUUID(),sectionId,version:updated.version,action:"CONTENT_STARTED",snapshot:{contentVersion:version,contentHash,status:"IN_PROGRESS"},changedById:actorId,correlationId}})}await this.audit(tx,actorId,correlationId,"PROPOSAL_TECHNICAL_CONTENT_VERSION_CREATED","PROPOSAL_TECHNICAL_SECTION",sectionId,{version,contentHash});return created});}
  async linkEvidence(sectionId:string,draft:TechnicalEvidenceLinkDraft,actorId:string,correlationId:string){return getDatabase().$transaction(async tx=>{const section=await this.currentSection(tx,sectionId);if(section.responsibleId!==actorId)throw new TechnicalReviewRuleError("Somente o responsável atual pode vincular evidências à seção.");const evidence=await tx.technicalEvidence.findFirst({where:{id:draft.technicalEvidenceId,status:"CURRENT"},include:{documentVersion:true}});if(!evidence)throw new TechnicalReviewNotFoundError("Evidência técnica vigente não encontrada.");const created=await tx.proposalTechnicalEvidenceLink.create({data:{id:randomUUID(),sectionId,technicalEvidenceId:evidence.id,evidenceVersion:evidence.version,evidenceType:evidence.type,evidenceNumber:evidence.number,documentVersionId:evidence.documentVersionId,documentFileHash:evidence.documentVersion.fileHash,locator:draft.locator,justification:draft.justification,createdBy:actorId,correlationId}});await this.audit(tx,actorId,correlationId,"PROPOSAL_TECHNICAL_EVIDENCE_LINKED","PROPOSAL_TECHNICAL_SECTION",sectionId,{evidenceId:evidence.id,evidenceVersion:evidence.version,documentFileHash:evidence.documentVersion.fileHash});return created});}
  async addComment(sectionId:string,draft:TechnicalCommentDraft,actorId:string,correlationId:string){return getDatabase().$transaction(async tx=>{await this.currentSection(tx,sectionId);await this.activeUser(tx,actorId);const created=await tx.proposalTechnicalReviewComment.create({data:{id:randomUUID(),sectionId,severity:draft.severity,comment:draft.comment,status:"OPEN",createdBy:actorId,correlationId}});await this.audit(tx,actorId,correlationId,"PROPOSAL_TECHNICAL_COMMENT_CREATED","PROPOSAL_TECHNICAL_SECTION",sectionId,{commentId:created.id,severity:created.severity});return created});}
  async resolveComment(sectionId:string,commentId:string,draft:TechnicalCommentResolution,actorId:string,correlationId:string){return getDatabase().$transaction(async tx=>{await this.currentSection(tx,sectionId);await this.activeUser(tx,actorId);const changed=await tx.proposalTechnicalReviewComment.updateMany({where:{id:commentId,sectionId,status:"OPEN"},data:{status:"RESOLVED",resolvedAt:new Date(),resolvedBy:actorId,resolution:draft.resolution}});if(changed.count!==1)throw new TechnicalReviewNotFoundError("Comentário aberto não encontrado.");await this.audit(tx,actorId,correlationId,"PROPOSAL_TECHNICAL_COMMENT_RESOLVED","PROPOSAL_TECHNICAL_SECTION",sectionId,{commentId,resolution:draft.resolution});return tx.proposalTechnicalReviewComment.findUniqueOrThrow({where:{id:commentId}})});}
  async review(sectionId:string,draft:TechnicalReviewDraft,actorId:string,correlationId:string){return getDatabase().$transaction(async tx=>{await this.currentSection(tx,sectionId);await this.activeUser(tx,actorId);const content=await tx.proposalTechnicalContentVersion.findFirst({where:{sectionId},orderBy:{version:"desc"}});if(!content)throw new TechnicalReviewRuleError("A revisão exige conteúdo técnico versionado.");const openComments=await tx.proposalTechnicalReviewComment.count({where:{sectionId,status:"OPEN"}});const evidenceCount=await tx.proposalTechnicalEvidenceLink.count({where:{sectionId}});if(draft.decision==="APPROVED"&&openComments>0)throw new TechnicalReviewRuleError("Resolva todos os comentários antes da aprovação.");if(draft.decision==="APPROVED"&&evidenceCount===0)throw new TechnicalReviewRuleError("A aprovação exige ao menos uma evidência técnica.");const previous=await tx.proposalTechnicalReview.findFirst({where:{sectionId},orderBy:{version:"desc"}});const version=(previous?.version??0)+1;const review=await tx.proposalTechnicalReview.create({data:{id:randomUUID(),sectionId,version,contentVersion:content.version,decision:draft.decision,justification:draft.justification,reviewedBy:actorId,correlationId}});const status=draft.decision==="APPROVED"?"COMPLETED":"IN_PROGRESS";const updated=await tx.proposalTechnicalSection.update({where:{id:sectionId},data:{status,version:{increment:1},updatedBy:actorId}});await tx.proposalTechnicalSectionHistory.create({data:{id:randomUUID(),sectionId,version:updated.version,action:"TECHNICAL_REVIEW_RECORDED",snapshot:{reviewVersion:version,contentVersion:content.version,decision:draft.decision,status},changedById:actorId,correlationId}});await this.audit(tx,actorId,correlationId,"PROPOSAL_TECHNICAL_REVIEW_RECORDED","PROPOSAL_TECHNICAL_SECTION",sectionId,{reviewVersion:version,contentVersion:content.version,decision:draft.decision});return review});}
  private async currentSection(tx:Prisma.TransactionClient,sectionId:string){const section=await tx.proposalTechnicalSection.findUnique({where:{id:sectionId},include:{component:{include:{proposalVersion:{include:{proposal:true}}}}}});if(!section)throw new TechnicalReviewNotFoundError();if(section.component.proposalVersion.version!==section.component.proposalVersion.proposal.version)throw new TechnicalReviewRuleError("Somente a versão atual da proposta pode ser elaborada ou revisada.");return section}
  private async activeUser(tx:Prisma.TransactionClient,id:string){const user=await tx.user.findFirst({where:{id,status:"ACTIVE"}});if(!user)throw new TechnicalReviewRuleError("A ação exige usuário ativo.");return user}
  private audit(tx:Prisma.TransactionClient,actorId:string,correlationId:string,action:string,entityType:string,entityId:string,metadata:Prisma.InputJsonValue){return tx.auditEvent.create({data:{id:randomUUID(),actorType:"USER",actorId,action,entityType,entityId,correlationId,outcome:"SUCCESS",origin:"proposal-review-service",metadata}})}
}
