"use client";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

export function AnalysisActions({ analysisId, users }: { analysisId: string; users: readonly { id: string; name: string }[] }) {
  const router = useRouter(); const [message, setMessage] = useState("");
  async function decide(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch(`/api/analyses/${analysisId}/decision`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision: form.get("decision"), justification: form.get("justification") }) }); const result = await response.json() as { error?: { message?: string } }; setMessage(response.ok ? "Decisão humana registrada." : result.error?.message ?? "Falha na decisão."); if (response.ok) router.refresh(); }
  async function reassign(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch(`/api/analyses/${analysisId}/assignee`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ assigneeId: form.get("assigneeId"), reason: form.get("reason") }) }); const result = await response.json() as { error?: { message?: string } }; setMessage(response.ok ? "Responsável reatribuído." : result.error?.message ?? "Falha na reatribuição."); if (response.ok) router.refresh(); }
  return <div className="mt-3 grid gap-2"><form className="flex flex-wrap gap-2" onSubmit={decide}><select className="rounded-lg border border-border px-2 py-2 text-xs" name="decision"><option value="VALIDATED">Validar</option><option value="REJECTED">Rejeitar</option></select><input className="min-w-56 flex-1 rounded-lg border border-border px-2 py-2 text-xs" name="justification" minLength={10} required placeholder="Justificativa humana"/><button className="rounded-lg bg-brand px-3 py-2 text-xs font-bold text-white">Registrar decisão</button></form><form className="flex flex-wrap gap-2" onSubmit={reassign}><select className="rounded-lg border border-border px-2 py-2 text-xs" name="assigneeId">{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><input className="min-w-56 flex-1 rounded-lg border border-border px-2 py-2 text-xs" name="reason" minLength={10} required placeholder="Motivo da reatribuição"/><button className="rounded-lg border border-brand px-3 py-2 text-xs font-bold text-brand">Reatribuir</button></form>{message && <span className="text-xs text-muted" role="status">{message}</span>}</div>;
}
