import Link from "next/link";
import { notFound } from "next/navigation";
import { getCurrentAuthorizationContext } from "@/core/authorization/authorization-context";
import { authorize } from "@/core/authorization/policy";
import { getDatabase } from "@/core/database/prisma";
import { CompetitionActForm,CompetitionAwardForm,CompetitionForm,CompetitionResultForm,MotiveCategoryForm,OfferForm,ParticipantForm,ResultValidationForm } from "./competition-forms";

const participantLabels:Record<string,string>={EXPECTED:"Esperado",PARTICIPATING:"Participando",WITHDRAWN:"Retirado"};
const actLabels:Record<string,string>={JUDGMENT:"Julgamento",DILIGENCE:"Diligência",APPEAL:"Recurso",COUNTERARGUMENT:"Contrarrazão",DECISION:"Decisão"};
const outcomeLabels:Record<string,string>={WIN:"Ganho",LOSS:"Perda",DISQUALIFICATION:"Desclassificação",CANCELLATION:"Cancelamento"};
const date=(value:Date)=>value.toLocaleDateString("pt-BR",{timeZone:"UTC"});

export default async function CompetitionsPage(){
  const authorization=await getCurrentAuthorizationContext(); if(!authorize(authorization,{permission:"competitions.read"}).allowed)notFound();
  const db=getDatabase(),canManage=authorize(authorization,{permission:"competitions.manage"}).allowed,canValidate=authorize(authorization,{permission:"competitions.validate-result"}).allowed,canReadDocuments=authorize(authorization,{permission:"documents.read"}).allowed;
  const[tenders,competitions,documents,categories]=await Promise.all([
    db.tender.findMany({include:{lots:true},orderBy:{code:"asc"}}),
    db.competition.findMany({include:{tender:true,tenderLot:true,participants:{include:{competitor:true,offers:{orderBy:{version:"asc"}}},orderBy:{createdAt:"asc"}},acts:{include:{participant:{include:{competitor:true}},documentVersion:{include:{document:true}}},orderBy:[{actDate:"asc"},{version:"asc"}]},results:{include:{winningParticipant:{include:{competitor:true}},motiveCategory:true,documentVersion:{include:{document:true}},validation:true,award:true},orderBy:{version:"asc"}}},orderBy:{createdAt:"desc"}}),
    canReadDocuments?db.managedDocument.findMany({include:{versions:{orderBy:{version:"desc"}}},orderBy:{title:"asc"}}):Promise.resolve([]),
    db.competitionMotiveCategory.findMany({orderBy:[{code:"asc"},{version:"asc"}]}),
  ]);
  const tenderOptions=tenders.map(tender=>({id:tender.id,label:`${tender.code} · ${tender.number}`,lots:tender.lots.map(lot=>({id:lot.id,label:`${lot.code} · ${lot.subject}`}))}));
  const documentOptions=documents.flatMap(document=>document.versions.map(version=>({id:version.id,label:`${document.type} · ${document.title} · v${version.version}`})));
  const latestCategories=categories.filter(category=>!categories.some(other=>other.categoryKey===category.categoryKey&&other.version>category.version));
  const activeCategories=latestCategories.filter(category=>category.status==="ACTIVE").map(category=>({id:category.id,label:`${category.code} · ${category.name} · v${category.version}`,outcome:category.applicableOutcome??undefined}));

  return <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6 px-6 py-10">
    <header><Link className="text-sm font-bold text-brand" href="/">← Início</Link><p className="mt-6 text-sm font-bold uppercase tracking-wider text-brand">Incremento I4 · BL-401/402/403</p><h1 className="mt-1 text-3xl font-bold">Concorrência, atos e resultados</h1><p className="mt-2 text-muted">Histórico documental completo, motivos governados e resultado oficial somente após validação humana.</p></header>
    {canManage&&<><CompetitionForm tenders={tenderOptions}/><MotiveCategoryForm latestCategories={latestCategories.map(item=>({id:item.id,label:`${item.code} · v${item.version} · ${item.status}`}))}/></>}
    <section className="grid gap-4"><h2 className="text-2xl font-bold">Concorrências registradas</h2>{competitions.map(competition=>{
      const latestActs=competition.acts.filter(act=>!competition.acts.some(other=>other.actKey===act.actKey&&other.version>act.version)),latestResult=competition.results.at(-1);
      const participants=competition.participants.map(item=>({id:item.id,label:item.competitor.legalName}));
      return <article className="rounded-2xl border border-border bg-surface p-6" key={competition.id}>
        <div className="flex flex-wrap justify-between gap-2"><div><p className="text-xs font-bold text-brand">{competition.tender.code} · {competition.tenderLot.code}</p><h3 className="mt-1 text-lg font-bold">{competition.tenderLot.subject}</h3></div><span className="text-xs font-bold">{competition.status}</span></div>
        <p className="mt-2 text-xs text-muted">Data {date(competition.competitionDate)} · fonte {competition.sourceReference} · referência {date(competition.sourceDate)}</p>
        <div className="mt-4 grid gap-3">{competition.participants.map(participant=>{const latest=participant.offers.at(-1);return <section className="rounded-xl border border-border p-4" key={participant.id}><div className="flex flex-wrap justify-between gap-2"><div><p className="font-bold">{participant.competitor.legalName}</p>{participant.competitor.tradeName&&<p className="text-xs text-muted">{participant.competitor.tradeName}</p>}</div><div className="text-right text-xs"><p className="font-bold">{participantLabels[participant.status]??participant.status}</p><p>{participant.factStatus==="CONFIRMED"?"Confirmado":"Estimado"}</p></div></div><p className="mt-2 text-xs text-muted">Fonte: {participant.sourceReference}</p><div className="mt-3 grid gap-2">{participant.offers.map(offer=><div className="rounded-lg bg-background p-3 text-xs" key={offer.id}><strong>v{offer.version} · {offer.currency} {offer.amount.toFixed(2)}</strong> · {offer.factStatus==="CONFIRMED"?"Confirmada":"Estimativa"}<p className="mt-1 text-muted">{date(offer.offerDate)} · {offer.sourceReference}</p></div>)}{!participant.offers.length&&<p className="text-xs text-muted">Nenhuma oferta registrada.</p>}</div>{canManage&&<OfferForm participantId={participant.id} latestOfferId={latest?.id}/>}</section>})}{!competition.participants.length&&<p className="text-xs text-muted">Nenhum participante registrado.</p>}</div>
        {canManage&&<ParticipantForm competitionId={competition.id}/>} 
        <section className="mt-6 border-t border-border pt-5"><h4 className="text-lg font-bold">Julgamentos, diligências e recursos</h4><div className="mt-3 grid gap-2">{competition.acts.map(act=><article className="rounded-xl bg-background p-4 text-sm" key={act.id}><div className="flex flex-wrap justify-between gap-2"><strong>{actLabels[act.type]??act.type} · v{act.version}</strong><span className="text-xs text-muted">{date(act.actDate)}</span></div><p className="mt-2">{act.summary}</p>{act.participant&&<p className="mt-1 text-xs">Participante: {act.participant.competitor.legalName}</p>}{act.type==="JUDGMENT"&&<p className="mt-1 text-xs">Classificação: {act.judgmentClassification} · Habilitação: {act.qualification} · Critério: {act.criterion}</p>}{act.deadlineAt&&<p className="mt-1 text-xs font-bold">Prazo: {act.deadlineAt.toLocaleString("pt-BR")}</p>}<p className="mt-2 break-all text-xs text-muted">Fonte: {act.sourceReference} · documento {canReadDocuments?`${act.documentVersion.document.title} v${act.documentVersion.version}`:act.documentFileHash}</p></article>)}{!competition.acts.length&&<p className="text-xs text-muted">Nenhum ato registrado.</p>}</div>{canManage&&canReadDocuments&&<CompetitionActForm competitionId={competition.id} participants={participants} documents={documentOptions} latestActs={latestActs.map(item=>({id:item.id,label:`${actLabels[item.type]??item.type} v${item.version} · ${date(item.actDate)}`}))}/>}</section>
        <section className="mt-6 border-t border-border pt-5"><h4 className="text-lg font-bold">Resultado e motivo</h4><div className="mt-3 grid gap-2">{competition.results.map(result=><article className="rounded-xl bg-background p-4 text-sm" key={result.id}><div className="flex flex-wrap justify-between gap-2"><strong>v{result.version} · {outcomeLabels[result.outcome]??result.outcome}</strong><span className={result.validation?"text-xs font-bold text-success":"text-xs font-bold text-muted"}>{result.validation?"VALIDADO":"AGUARDANDO VALIDAÇÃO"}</span></div><p className="mt-2">{result.justification}</p><p className="mt-1 text-xs">Motivo: {result.motiveCategory.code} · {result.motiveCategory.name} v{result.motiveCategory.version}</p>{result.winningParticipant&&<p className="mt-1 text-xs">Vencedor: {result.winningParticipant.competitor.legalName}</p>}<p className="mt-2 break-all text-xs text-muted">{date(result.resultDate)} · {result.sourceReference} · documento {canReadDocuments?`${result.documentVersion.document.title} v${result.documentVersion.version}`:result.documentFileHash}</p>{result.validation&&<p className="mt-2 text-xs font-bold">Validação humana em {result.validation.validatedAt.toLocaleString("pt-BR")} · {result.validation.note}</p>}{result.award&&<p className="mt-2 text-xs font-bold">Valor conquistado: {result.award.currency} {result.award.contractValue.toFixed(2)} · evidência {result.award.documentFileHash}</p>}{canValidate&&!result.validation&&latestResult?.id===result.id&&<ResultValidationForm resultId={result.id}/>} {canManage&&canReadDocuments&&result.validation&&result.outcome==="WIN"&&latestResult?.id===result.id&&!result.award&&<CompetitionAwardForm resultId={result.id} documents={documentOptions}/>}</article>)}{!competition.results.length&&<p className="text-xs text-muted">Nenhum resultado registrado.</p>}</div>{canManage&&canReadDocuments&&<CompetitionResultForm competitionId={competition.id} previousResultId={latestResult?.id} participants={participants} categories={activeCategories} documents={documentOptions}/>}</section>
      </article>})}{!competitions.length&&<p className="rounded-2xl border border-border bg-surface p-8 text-center text-muted">Nenhuma concorrência registrada.</p>}</section>
  </main>;
}
