import Link from "next/link";
import { notFound } from "next/navigation";
import { MetricCard } from "@/components/ui/metric-card";
import { PageHeader } from "@/components/ui/page-header";
import { getCurrentAuthorizationContext } from "@/core/authorization/authorization-context";
import { authorize } from "@/core/authorization/policy";
import { getDatabase } from "@/core/database/prisma";
import { indicatorRowFilter } from "@/modules/indicators/application/indicator-row-security";
import { IndicatorApprovalForm, IndicatorCalculationForm, IndicatorForm, IndicatorPublicationForm, IndicatorReconciliationForm } from "./indicator-forms";

type SourceMapping = { logicalTable: string; field: string; validStatuses: string[] };
const methodLabels: Record<string,string>={PIPELINE_COUNT:"Quantidade no pipeline",PIPELINE_VALUE:"Valor do pipeline",RESULT_CONVERSION_RATE:"Conversão por resultado",FINANCIAL_CONVERSION_RATE:"Conversão financeira",AVERAGE_DISCOUNT_PERCENT:"Desconto médio",AVERAGE_MARGIN_PERCENT:"Margem média"};
const moneyMethods=new Set(["PIPELINE_VALUE","FINANCIAL_CONVERSION_RATE","AVERAGE_DISCOUNT_PERCENT","AVERAGE_MARGIN_PERCENT"]);
const date=(value:Date)=>value.toLocaleDateString("pt-BR",{timeZone:"UTC"});

export default async function IndicatorsPage(){
  const auth=await getCurrentAuthorizationContext();if(!auth||!authorize(auth,{permission:"indicators.read"}).allowed)notFound();
  const db=getDatabase(),canManage=authorize(auth,{permission:"indicators.manage"}).allowed,canApprove=authorize(auth,{permission:"indicators.approve"}).allowed,canCalculate=authorize(auth,{permission:"indicators.calculate"}).allowed,canReconcile=authorize(auth,{permission:"indicators.reconcile"}).allowed,canPublish=authorize(auth,{permission:"indicators.publish"}).allowed;
  const [definitions,users]=await Promise.all([db.indicatorDefinition.findMany({where:indicatorRowFilter(auth),include:{approval:true,snapshots:{include:{baselineReconciliations:{include:{observedSnapshot:true,publication:true},orderBy:{checkedAt:"desc"}}},orderBy:{calculatedAt:"desc"}}},orderBy:[{code:"asc"},{version:"asc"}]}),db.user.findMany({where:{status:"ACTIVE"},orderBy:{displayName:"asc"}})]);
  const userNames=new Map(users.map(user=>[user.id,user.displayName])),latest=definitions.filter(item=>!definitions.some(other=>other.indicatorKey===item.indicatorKey&&other.version>item.version));
  const approved=latest.filter(item=>Boolean(item.approval)).length,snapshots=latest.reduce((sum,item)=>sum+item.snapshots.length,0),publications=latest.reduce((sum,item)=>sum+item.snapshots.reduce((snapshotSum,snapshot)=>snapshotSum+snapshot.baselineReconciliations.filter(reconciliation=>Boolean(reconciliation.publication)).length,0),0),divergences=latest.reduce((sum,item)=>sum+item.snapshots.reduce((snapshotSum,snapshot)=>snapshotSum+snapshot.baselineReconciliations.filter(reconciliation=>reconciliation.status!=="MATCH").length,0),0);
  return <main className="mx-auto flex w-full max-w-[1500px] flex-1 flex-col gap-6 px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <PageHeader action={canManage?<Link className="inline-flex h-11 items-center gap-2 rounded-lg bg-brand px-5 text-sm font-bold text-white shadow-md shadow-blue-900/15" href="#configurar-indicador"><span className="text-lg font-normal">＋</span> Novo indicador</Link>:undefined} eyebrow="Inteligência" icon="chart" subtitle="Indicadores consolidados, rastreáveis e vinculados às fontes operacionais do G-SIPRO." title="Inteligência e KPIs"/>
    <section aria-label="Indicadores da inteligência" className="grid gap-5 sm:grid-cols-2 xl:grid-cols-5"><MetricCard description="Definições vigentes no catálogo" icon="chart" title="Indicadores cadastrados" tone="blue" value={latest.length}/><MetricCard description="Indicadores com aprovação formal" icon="target" title="Indicadores aprovados" tone="green" value={approved}/><MetricCard description="Cálculos imutáveis registrados" icon="refresh" title="Snapshots calculados" tone="violet" value={snapshots}/><MetricCard description="Resultados conciliados e publicados" icon="send" title="KPIs publicados" tone="green" value={publications}/><MetricCard description="Conciliações que exigem revisão" icon="clock" title="Divergências abertas" tone={divergences?"red":"slate"} value={divergences}/></section>
    {canManage&&<details className="scroll-mt-6 rounded-xl border border-slate-200 bg-white shadow-sm" id="configurar-indicador"><summary className="cursor-pointer px-5 py-4 text-sm font-black uppercase tracking-wide text-slate-800">Configurar ou versionar indicador</summary><div className="border-t border-slate-200 p-5"><IndicatorForm users={users.map(user=>({id:user.id,label:user.displayName}))} latestDefinitions={latest.map(item=>({id:item.id,label:`${item.code} · v${item.version}`}))}/></div></details>}
    <div><h2 className="text-base font-black uppercase tracking-wide text-slate-900">Catálogo de indicadores</h2><p className="mt-1 text-xs text-slate-500">Definições, cálculos, conciliações e publicações preservadas por versão.</p></div><section className="grid gap-4">{definitions.map(definition=>{const sources=definition.sourceMappings as unknown as SourceMapping[],dimensions=definition.dimensions as string[],isLatest=latest.some(item=>item.id===definition.id),method=definition.calculationMethod;return <article className="rounded-xl border border-border bg-surface p-6 shadow-[0_3px_14px_rgba(15,23,42,0.05)]" key={definition.id}>
      <div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold text-brand">{definition.code} · versão {definition.version}</p><h2 className="mt-1 text-xl font-bold">{definition.name}</h2><p className="mt-1 text-xs text-muted">{method?methodLabels[method]:"Definição legada — crie uma revisão executável para calcular"}</p></div><span className={definition.approval?"text-xs font-bold text-brand":"text-xs font-bold text-muted"}>{definition.approval?"APROVADO":"RASCUNHO"}</span></div>
      <p className="mt-3 text-sm">{definition.purpose}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-background p-4 text-xs"><strong>Fórmula</strong><p className="mt-2"><b>Numerador:</b> {definition.numeratorDefinition}</p><p className="mt-1"><b>Denominador:</b> {definition.denominatorDefinition}</p><p className="mt-1"><b>Tratamento:</b> {definition.treatmentDefinition}</p><p className="mt-1"><b>Granularidade:</b> {definition.granularity}</p></div><div className="rounded-xl bg-background p-4 text-xs"><strong>Governança</strong><p className="mt-2">Proprietário: {userNames.get(definition.ownerId)??definition.ownerId}</p><p>Vigência: {date(definition.effectiveFrom)}</p><p>Atualização: {definition.refreshPeriodicity} · {definition.refreshTime}</p><p>Qualidade: {definition.qualityTest} · {definition.qualityTolerance}</p><p>Responsável: {userNames.get(definition.qualityOwnerId)??definition.qualityOwnerId}</p></div><div className="rounded-xl bg-background p-4 text-xs"><strong>Fontes rastreáveis</strong>{sources.map((source,index)=><p className="mt-2" key={`${source.logicalTable}-${source.field}-${index}`}>{source.logicalTable}.{source.field} · {source.validStatuses.join(", ")}</p>)}</div><div className="rounded-xl bg-background p-4 text-xs"><strong>Dimensões e segurança</strong><p className="mt-2">{dimensions.join(" · ")}</p><p className="mt-2">Acesso: {definition.accessRule}</p><p>Linha: {definition.rowSecurityRule}</p></div></div>
      <p className="mt-3 text-xs text-muted">Motivo da versão: {definition.changeReason}</p>{definition.approval&&<p className="mt-2 text-xs font-bold">Aprovado em {definition.approval.approvedAt.toLocaleString("pt-BR")} · {definition.approval.note}</p>}{canApprove&&isLatest&&!definition.approval&&<IndicatorApprovalForm definitionId={definition.id}/>} {canCalculate&&isLatest&&Boolean(definition.approval)&&method&&<IndicatorCalculationForm definitionId={definition.id} requiresCurrency={moneyMethods.has(method)}/>} 
      {!!definition.snapshots.length&&<div className="mt-4 grid gap-2"><h3 className="text-sm font-bold">Snapshots auditáveis</h3>{definition.snapshots.map(snapshot=><div className="rounded-xl bg-background p-3 text-xs" key={snapshot.id}><div className="flex flex-wrap justify-between gap-2"><strong>{snapshot.value.toFixed(snapshot.unit==="PERCENT"?4:2)} {snapshot.unit==="PERCENT"?"%":snapshot.unit==="CURRENCY"?(snapshot.currency??""):"registros"}</strong><span>{date(snapshot.periodStart)} a {date(snapshot.periodEnd)}</span></div><p className="mt-1">Numerador {snapshot.numerator.toFixed(4)}{snapshot.denominator!==null?` · denominador ${snapshot.denominator.toFixed(4)}`:""} · {snapshot.sourceRecordCount} fontes</p><p className="mt-1 break-all font-mono text-[10px] text-muted">SHA-256 {snapshot.payloadHash}</p>{snapshot.baselineReconciliations.map(item=><div className="mt-2 rounded-lg border border-border p-2" key={item.id}><strong className={item.status==="MATCH"?"text-success":"text-danger"}>{item.status==="MATCH"?"CONCILIADO":"DIVERGENTE"}</strong><span> · {item.checkedAt.toLocaleString("pt-BR")} · Δ valor {item.valueDifference.toFixed(8)} · Δ fontes {item.sourceCountDifference}</span><p className="mt-1">{item.note}</p><p className="mt-1 break-all font-mono text-[10px] text-muted">Observação {item.observedSnapshot.payloadHash}</p>{item.publication?<div className="mt-2 rounded-lg bg-surface p-2"><strong>PUBLICADO · qualidade {item.publication.qualityState}</strong><p>Dados atualizados em {item.publication.dataUpdatedAt.toLocaleString("pt-BR")} · publicação {item.publication.publishedAt.toLocaleString("pt-BR")}</p><p className="break-all font-mono text-[10px] text-muted">Linhagem {item.publication.lineageHash}</p></div>:canPublish&&isLatest&&item.status==="MATCH"&&<IndicatorPublicationForm reconciliationId={item.id}/>}</div>)}{canReconcile&&isLatest&&<IndicatorReconciliationForm snapshotId={snapshot.id}/>}</div>)}</div>}
    </article>})}{!definitions.length&&<p className="rounded-2xl border border-border bg-surface p-8 text-center text-muted">Nenhum indicador definido. Fórmulas não serão inferidas automaticamente.</p>}</section>
  </main>;
}
