import{randomUUID}from"node:crypto";import{getDatabase}from"@/core/database/prisma";import{Prisma}from"@/generated/prisma/client";import type{AiExtractionContext,AiExtractionRepository}from"../application/ai-extraction-service";import{AiExtractionRuleError,type AiExtractionResult,type ExtractionSource}from"../domain/ai-extraction";
/**
 * Colunas de procedência conforme a origem dos bytes.
 *
 * O banco tem CHECK de exclusividade: ou a versão documental, ou o bloco
 * externo completo. Montar isto num lugar só evita gravar meia procedência,
 * que o CHECK recusaria com uma mensagem difícil de rastrear.
 */
const procedencia=(source:ExtractionSource)=>source.kind==="ARCHIVED"
  ?{documentVersionId:source.documentVersionId,sourceUri:null,sourceFilename:null,sourceMimeType:null,sourceSizeBytes:null,sourceFetchedAt:null}
  :{documentVersionId:null,sourceUri:source.uri,sourceFilename:source.filename,sourceMimeType:source.mimeType,sourceSizeBytes:BigInt(source.sizeBytes),sourceFetchedAt:source.fetchedAt};
export class PrismaAiExtractionRepository implements AiExtractionRepository{
async context(definitionId:string,documentVersionId:string){const db=getDatabase(),[definition,documentVersion]=await Promise.all([db.aiUseCaseDefinition.findUnique({where:{id:definitionId},include:{approval:true,modelVersion:true}}),db.managedDocumentVersion.findUnique({where:{id:documentVersionId},include:{document:true}})]);if(!definition||!documentVersion)return undefined;const latest=await db.aiUseCaseDefinition.findFirst({where:{useCaseKey:definition.useCaseKey},orderBy:{version:"desc"}});return{definition:{id:definition.id,promptTemplate:definition.promptTemplate,promptHash:definition.promptHash,authorizedSources:definition.authorizedSources,modelVersionId:definition.modelVersionId,approval:Boolean(definition.approval),isLatest:latest?.id===definition.id},model:{id:definition.modelVersion.id,provider:definition.modelVersion.provider,providerModelVersion:definition.modelVersion.providerModelVersion,serviceType:definition.modelVersion.serviceType,status:definition.modelVersion.status},source:{kind:"ARCHIVED" as const,documentVersionId:documentVersion.id,fileHash:documentVersion.fileHash,mimeType:documentVersion.mimeType,documentType:documentVersion.document.type,title:documentVersion.document.title}}}
/**
 * Contexto de fonte efêmera. Não vai ao acervo: a procedência chega pronta,
 * já com o hash calculado sobre os bytes pelo próprio serviço.
 */
async ephemeralContext(definitionId:string,source:Extract<ExtractionSource,{kind:"EPHEMERAL"}>){const db=getDatabase(),definition=await db.aiUseCaseDefinition.findUnique({where:{id:definitionId},include:{approval:true,modelVersion:true}});if(!definition)return undefined;const latest=await db.aiUseCaseDefinition.findFirst({where:{useCaseKey:definition.useCaseKey},orderBy:{version:"desc"}});return{definition:{id:definition.id,promptTemplate:definition.promptTemplate,promptHash:definition.promptHash,authorizedSources:definition.authorizedSources,modelVersionId:definition.modelVersionId,approval:Boolean(definition.approval),isLatest:latest?.id===definition.id},model:{id:definition.modelVersion.id,provider:definition.modelVersion.provider,providerModelVersion:definition.modelVersion.providerModelVersion,serviceType:definition.modelVersion.serviceType,status:definition.modelVersion.status},source}}
async begin(r:{idempotencyKey:string;requestedFields:string[];instructions?:string},inputHash:string,c:AiExtractionContext,actor:string,correlation:string){const db=getDatabase(),existing=await db.aiExtractionExecution.findUnique({where:{idempotencyKey:r.idempotencyKey}});if(existing)return{id:existing.id,status:existing.status,inputHash:existing.inputHash,reused:true};const created=await db.$transaction(async tx=>{const item=await tx.aiExtractionExecution.create({data:{id:randomUUID(),idempotencyKey:r.idempotencyKey,definitionId:c.definition.id,modelVersionId:c.model.id,...procedencia(c.source),documentFileHash:c.source.fileHash,requestedFields:r.requestedFields,instructions:r.instructions,inputHash,status:"RUNNING",startedAt:new Date(),createdBy:actor,correlationId:correlation}});await tx.auditEvent.create({data:{id:randomUUID(),actorType:"USER",actorId:actor,action:"AI_EXTRACTION_STARTED",entityType:"AI_EXTRACTION_EXECUTION",entityId:item.id,correlationId:correlation,outcome:"SUCCESS",origin:"ai-extraction",metadata:{definitionId:item.definitionId,modelVersionId:item.modelVersionId,sourceKind:c.source.kind,documentVersionId:item.documentVersionId,sourceUri:item.sourceUri,documentFileHash:item.documentFileHash,inputHash:item.inputHash}}});return item});return{id:created.id,status:created.status,inputHash:created.inputHash,reused:false}}
async succeed(id:string,output:AiExtractionResult,providerResponseId:string,c:AiExtractionContext,actor:string,correlation:string){await getDatabase().$transaction(async tx=>{await tx.aiExtractionEvidence.createMany({data:output.evidence.map(item=>({id:randomUUID(),executionId:id,documentVersionId:c.source.kind==="ARCHIVED"?c.source.documentVersionId:null,documentFileHash:c.source.fileHash,excerpt:item.excerpt,locator:item.locator}))});await tx.aiExtractionExecution.update({where:{id},data:{status:"SUCCEEDED",output:output.content as Prisma.InputJsonValue,confidence:output.confidence,limitations:output.limitations,providerResponseId,completedAt:new Date()}});await tx.auditEvent.create({data:{id:randomUUID(),actorType:"USER",actorId:actor,action:"AI_EXTRACTION_SUCCEEDED",entityType:"AI_EXTRACTION_EXECUTION",entityId:id,correlationId:correlation,outcome:"SUCCESS",origin:"ai-extraction",metadata:{providerResponseId,confidence:output.confidence,evidenceCount:output.evidence.length,assistive:true}}})})}
async fail(id:string,code:string,message:string,actor:string,correlation:string){const current=await getDatabase().aiExtractionExecution.findUnique({where:{id}});if(!current||current.status!=="RUNNING")throw new AiExtractionRuleError("A execução não pode mais ser atualizada.");await getDatabase().$transaction(async tx=>{await tx.aiExtractionExecution.update({where:{id},data:{status:"FAILED",errorCode:code,errorMessage:message,completedAt:new Date()}});await tx.auditEvent.create({data:{id:randomUUID(),actorType:"USER",actorId:actor,action:"AI_EXTRACTION_FAILED",entityType:"AI_EXTRACTION_EXECUTION",entityId:id,correlationId:correlation,outcome:"FAILURE",origin:"ai-extraction",metadata:{errorCode:code}}})})}
get(id:string){return getDatabase().aiExtractionExecution.findUnique({where:{id},include:{definition:{select:{code:true,name:true,version:true,promptHash:true}},modelVersion:{select:{provider:true,modelName:true,providerModelVersion:true,version:true}},documentVersion:{include:{document:{select:{type:true,title:true}}}},evidence:true}})}
}
