import { getDatabase } from "../src/core/database/prisma";
import { CompetitionService } from "../src/modules/competitions/application/competition-service";
import { PrismaCompetitionRepository } from "../src/modules/competitions/infrastructure/prisma-competition-repository";

async function main(){
  if(!process.env.DATABASE_URL?.match(/@(?:localhost|127\.0\.0\.1):5433\/gsipro(?:\?|$)/))throw new Error("Smoke permitido somente no PostgreSQL local G-SIPRO em 5433.");
  const db=getDatabase(),actor=await db.user.findFirstOrThrow({where:{status:"ACTIVE",email:{not:"aprovador.i3@gsipro.local"}}}),tender=await db.tender.findUniqueOrThrow({where:{code:"ED-TESTE-I3-001"},include:{lots:true}}),lot=tender.lots[0],service=new CompetitionService(new PrismaCompetitionRepository());
  let competition=await db.competition.findUnique({where:{tenderLotId:lot.id}});if(!competition)competition=await service.createCompetition({tenderId:tender.id,tenderLotId:lot.id,competitionDate:"2026-07-19",sourceReference:"Ata sintética pública do BL-401",sourceDate:"2026-07-19"},actor.id) as typeof competition;
  let participant=await db.competitionParticipant.findFirst({where:{competitionId:competition!.id,competitor:{normalizedName:"concorrente sintetico i4"}}});if(!participant){const created=await service.addParticipant(competition!.id,{legalName:"Concorrente Sintético I4",tradeName:"CSI4",knownNames:["Concorrente I4"],status:"PARTICIPATING",factStatus:"CONFIRMED",sourceReference:"Ata sintética pública do BL-401",sourceDate:"2026-07-19"},actor.id) as {id:string};participant=await db.competitionParticipant.findUniqueOrThrow({where:{id:created.id}})}
  let offers=await db.competitionOffer.findMany({where:{participantId:participant.id},orderBy:{version:"asc"}});if(!offers.length){await service.addOffer(participant.id,{amount:"95000.0000",currency:"BRL",offerDate:"2026-07-19",factStatus:"ESTIMATED",sourceReference:"Leitura preliminar da sessão",sourceDate:"2026-07-19"},actor.id);offers=await db.competitionOffer.findMany({where:{participantId:participant.id},orderBy:{version:"asc"}})}if(offers.length===1){await service.addOffer(participant.id,{previousOfferId:offers[0].id,amount:"94000.0000",currency:"BRL",offerDate:"2026-07-19",factStatus:"CONFIRMED",sourceReference:"Ata final da sessão",sourceDate:"2026-07-19"},actor.id);offers=await db.competitionOffer.findMany({where:{participantId:participant.id},orderBy:{version:"asc"}})}
  let immutable=false;try{await db.$executeRaw`UPDATE competition_offers SET amount=1 WHERE id=${offers[0].id}::uuid`}catch{immutable=true}let duplicateBlocked=false;try{await service.addParticipant(competition!.id,{legalName:"Concorrente Sintético I4",status:"PARTICIPATING",factStatus:"CONFIRMED",sourceReference:"Fonte duplicada",sourceDate:"2026-07-19"},actor.id)}catch{duplicateBlocked=true}
  const result={lotLinked:competition!.tenderId===tender.id&&competition!.tenderLotId===lot.id,participantPerLot:participant.competitionId===competition!.id,estimatedSeparated:offers[0].factStatus==="ESTIMATED",confirmedRevision:offers[1]?.factStatus==="CONFIRMED"&&offers[1].previousVersionId===offers[0].id,sourcePreserved:offers.every(item=>item.sourceReference.length>2),historyPreserved:offers.length===2,immutable,duplicateBlocked,audited:(await db.auditEvent.count({where:{entityType:{in:["COMPETITION","COMPETITION_PARTICIPANT","COMPETITION_OFFER"]}}}))>=4};console.log(JSON.stringify(result));if(!Object.values(result).every(Boolean))throw new Error("Smoke do BL-401 não confirmou todas as invariantes.");await db.$disconnect();
}
main().catch(error=>{console.error(error instanceof Error?error.message:"Smoke failed");process.exitCode=1});
