import { getDatabase } from "../src/core/database/prisma";
import { TechnicalReviewService } from "../src/modules/proposal-reviews/application/technical-review-service";
import { PrismaTechnicalReviewRepository } from "../src/modules/proposal-reviews/infrastructure/prisma-technical-review-repository";

async function main(){
  if(!process.env.DATABASE_URL?.match(/@(?:localhost|127\.0\.0\.1):5433\/gsipro(?:\?|$)/))throw new Error("Smoke permitido somente no PostgreSQL local G-SIPRO em 5433.");
  const db=getDatabase();const actor=await db.user.findFirstOrThrow({where:{status:"ACTIVE"}});const proposal=await db.proposal.findUniqueOrThrow({where:{code:"PROP-TESTE-I3-001"}});const current=await db.proposalVersion.findUniqueOrThrow({where:{proposalId_version:{proposalId:proposal.id,version:proposal.version}},include:{components:{include:{technicalSections:true}}}});const section=current.components.find(item=>item.type==="TECHNICAL")?.technicalSections[0];if(!section)throw new Error("Seção sintética do BL-303 não encontrada.");const evidence=await db.technicalEvidence.findFirstOrThrow({where:{status:"CURRENT"}});const service=new TechnicalReviewService(new PrismaTechnicalReviewRepository());
  const approved=await db.proposalTechnicalReview.findFirst({where:{sectionId:section.id,decision:"APPROVED"}});let criticalGate=true;
  if(!approved){if(!await db.proposalTechnicalContentVersion.findFirst({where:{sectionId:section.id}}))await service.addContent(section.id,{content:"A metodologia executiva contempla mobilização, planejamento, execução controlada e verificação final dos serviços.",reason:"Conteúdo sintético controlado para validar o BL-304."},actor.id);if(!await db.proposalTechnicalEvidenceLink.findFirst({where:{sectionId:section.id,technicalEvidenceId:evidence.id}}))await service.linkEvidence(section.id,{technicalEvidenceId:evidence.id,locator:"Documento integral",justification:"Evidência vigente comprova experiência compatível com a metodologia."},actor.id);let comment=await db.proposalTechnicalReviewComment.findFirst({where:{sectionId:section.id,comment:"Pendência crítica sintética do BL-304."}});if(!comment){await service.addComment(section.id,{severity:"CRITICAL",comment:"Pendência crítica sintética do BL-304."},actor.id);comment=await db.proposalTechnicalReviewComment.findFirstOrThrow({where:{sectionId:section.id,comment:"Pendência crítica sintética do BL-304."}})}try{await service.review(section.id,{decision:"APPROVED",justification:"Tentativa bloqueada por pendência crítica aberta."},actor.id);criticalGate=false}catch{}if(comment.status==="OPEN")await service.resolveComment(section.id,comment.id,{resolution:"Pendência crítica corrigida e conferida humanamente."},actor.id);await service.review(section.id,{decision:"APPROVED",justification:"Conteúdo, evidência e resolução conferidos humanamente."},actor.id);}
  const record=await db.proposalTechnicalSection.findUniqueOrThrow({where:{id:section.id},include:{contents:true,evidences:true,comments:true,reviews:true}});let contentImmutable=false;try{await db.$executeRaw`UPDATE "proposal_technical_content_versions" SET "content"='adulterado' WHERE "sectionId"=${section.id}::uuid`}catch{contentImmutable=true}let evidenceImmutable=false;try{await db.$executeRaw`UPDATE "proposal_technical_evidence_links" SET "locator"='adulterado' WHERE "sectionId"=${section.id}::uuid`}catch{evidenceImmutable=true}let reviewImmutable=false;try{await db.$executeRaw`UPDATE "proposal_technical_reviews" SET "decision"='CHANGES_REQUIRED' WHERE "sectionId"=${section.id}::uuid`}catch{reviewImmutable=true}const audits=await db.auditEvent.count({where:{entityType:"PROPOSAL_TECHNICAL_SECTION",entityId:section.id,action:{in:["PROPOSAL_TECHNICAL_CONTENT_VERSION_CREATED","PROPOSAL_TECHNICAL_EVIDENCE_LINKED","PROPOSAL_TECHNICAL_COMMENT_CREATED","PROPOSAL_TECHNICAL_COMMENT_RESOLVED","PROPOSAL_TECHNICAL_REVIEW_RECORDED"]}}});const result={contentVersioned:record.contents.length>0&&record.contents[0]!.contentHash.length===64,evidenceSpecific:record.evidences.length>0&&record.evidences[0]!.documentFileHash.length===64,criticalGate,commentsResolved:record.comments.every(item=>item.status==="RESOLVED"),humanReview:record.reviews.some(item=>item.decision==="APPROVED"),sectionCompleted:record.status==="COMPLETED",contentImmutable,evidenceImmutable,reviewImmutable,audits};console.log(JSON.stringify(result));if(!Object.values(result).every(value=>typeof value==="number"?value>=5:value))throw new Error("Smoke BL-304 não confirmou todas as invariantes.");await db.$disconnect();
}
main().catch(error=>{console.error(error instanceof Error?error.message:"Smoke failed");process.exitCode=1});
