"use client";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

type Option = Readonly<{ id: string; label: string }>;
export function TechnicalSectionForm({ proposalId, users, requirements, nextPosition }: { proposalId: string; users: ReadonlyArray<Option>; requirements: ReadonlyArray<Option>; nextPosition: number }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setBusy(true); setMessage(""); const response = await fetch(`/api/proposals/${proposalId}/technical-sections`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: form.get("type"), title: form.get("title"), position: form.get("position"), responsibleId: form.get("responsibleId"), requirementIds: form.getAll("requirementIds") }) }); const result = await response.json() as { error?: { message?: string } }; setBusy(false); setMessage(response.ok ? "Seção técnica criada com responsável e fontes preservados." : result.error?.message ?? "Falha ao criar seção."); if (response.ok) { formElement.reset(); router.refresh(); } }
  if (!users.length) return <p className="mt-4 text-xs font-bold text-amber-800">É necessário um usuário ativo para atribuir a seção.</p>;
  return <form className="mt-4 grid gap-3 rounded-xl border border-border p-4" onSubmit={submit}><div className="flex items-center justify-between"><h4 className="text-sm font-bold">Nova seção técnica</h4><span className="text-xs text-muted">BL-303</span></div><div className="grid gap-3 md:grid-cols-3"><label className="grid gap-1 text-xs font-bold">Tipo<input className="rounded-lg border border-border px-3 py-2 font-normal" maxLength={80} name="type" placeholder="Metodologia, equipe…" required /></label><label className="grid gap-1 text-xs font-bold md:col-span-2">Título<input className="rounded-lg border border-border px-3 py-2 font-normal" maxLength={200} name="title" required /></label><label className="grid gap-1 text-xs font-bold">Ordem<input className="rounded-lg border border-border px-3 py-2 font-normal" defaultValue={nextPosition} min={1} name="position" type="number" required /></label><label className="grid gap-1 text-xs font-bold md:col-span-2">Responsável<select className="rounded-lg border border-border px-3 py-2 font-normal" name="responsibleId" required>{users.map(user => <option key={user.id} value={user.id}>{user.label}</option>)}</select></label></div>{requirements.length > 0 && <label className="grid gap-1 text-xs font-bold">Requisitos validados de origem<select className="min-h-28 rounded-lg border border-border px-3 py-2 font-normal" multiple name="requirementIds">{requirements.map(requirement => <option key={requirement.id} value={requirement.id}>{requirement.label}</option>)}</select><span className="font-normal text-muted">Use Ctrl para selecionar mais de um requisito.</span></label>}<button className="w-fit rounded-lg bg-brand px-4 py-2 text-sm font-bold text-white" disabled={busy}>{busy ? "Criando…" : "Criar seção"}</button>{message && <p className="text-xs text-muted" role="status">{message}</p>}</form>;
}

export function TechnicalSectionControlForm({ proposalId, section, users }: { proposalId: string; section: Readonly<{ id: string; responsibleId: string; status: string; version: number }>; users: ReadonlyArray<Option> }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setMessage(""); const response = await fetch(`/api/proposals/${proposalId}/technical-sections/${section.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ responsibleId: form.get("responsibleId"), status: form.get("status"), version: section.version }) }); const result = await response.json() as { error?: { message?: string } }; setBusy(false); setMessage(response.ok ? "Responsável e status atualizados." : result.error?.message ?? "Falha ao atualizar seção."); if (response.ok) router.refresh(); }
  return <form className="mt-3 grid gap-2 md:grid-cols-[1fr_1fr_auto]" onSubmit={submit}><select className="rounded-lg border border-border px-3 py-2 text-xs" defaultValue={section.responsibleId} name="responsibleId">{users.map(user => <option key={user.id} value={user.id}>{user.label}</option>)}</select><select className="rounded-lg border border-border px-3 py-2 text-xs" defaultValue={section.status} name="status"><option value="DRAFT">Rascunho</option><option value="IN_PROGRESS">Em elaboração</option><option value="IN_REVIEW">Em revisão</option><option value="COMPLETED">Concluída</option></select><button className="rounded-lg border border-brand px-3 py-2 text-xs font-bold text-brand" disabled={busy}>{busy ? "Salvando…" : "Atualizar"}</button>{message && <p className="text-xs text-muted md:col-span-3" role="status">{message}</p>}</form>;
}
