CREATE TYPE "DeadlineStatus" AS ENUM ('PENDING_CONFIRMATION', 'CONFIRMED', 'COMPLETED', 'CANCELLED');
CREATE TYPE "DeadlineAlertStatus" AS ENUM ('SCHEDULED', 'ACKNOWLEDGED', 'CANCELLED');
CREATE TABLE "tender_deadlines" ("id" UUID NOT NULL,"tenderId" UUID NOT NULL,"requirementId" UUID,"event" VARCHAR(200) NOT NULL,"dueAt" TIMESTAMPTZ(6) NOT NULL,"timeZone" VARCHAR(80) NOT NULL,"source" VARCHAR(500) NOT NULL,"critical" BOOLEAN NOT NULL DEFAULT false,"responsibleId" UUID NOT NULL,"status" "DeadlineStatus" NOT NULL DEFAULT 'PENDING_CONFIRMATION',"confirmedAt" TIMESTAMPTZ(6),"confirmedById" UUID,"version" INTEGER NOT NULL DEFAULT 1,"createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdBy" UUID NOT NULL,"updatedAt" TIMESTAMPTZ(6) NOT NULL,"updatedBy" UUID NOT NULL,CONSTRAINT "tender_deadlines_pkey" PRIMARY KEY("id"));
CREATE TABLE "deadline_alerts" ("id" UUID NOT NULL,"deadlineId" UUID NOT NULL,"scheduledAt" TIMESTAMPTZ(6) NOT NULL,"status" "DeadlineAlertStatus" NOT NULL DEFAULT 'SCHEDULED',"createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdBy" UUID NOT NULL,CONSTRAINT "deadline_alerts_pkey" PRIMARY KEY("id"));
CREATE TABLE "deadline_history" ("id" UUID NOT NULL,"deadlineId" UUID NOT NULL,"version" INTEGER NOT NULL,"action" VARCHAR(80) NOT NULL,"changes" JSONB NOT NULL,"reason" VARCHAR(1000),"changedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"changedById" UUID NOT NULL,"correlationId" UUID NOT NULL,CONSTRAINT "deadline_history_pkey" PRIMARY KEY("id"));
CREATE INDEX "tender_deadlines_tenderId_status_dueAt_idx" ON "tender_deadlines"("tenderId","status","dueAt");
CREATE INDEX "tender_deadlines_responsibleId_status_dueAt_idx" ON "tender_deadlines"("responsibleId","status","dueAt");
CREATE INDEX "tender_deadlines_requirementId_idx" ON "tender_deadlines"("requirementId");
CREATE INDEX "deadline_alerts_status_scheduledAt_idx" ON "deadline_alerts"("status","scheduledAt");
CREATE UNIQUE INDEX "deadline_alerts_deadlineId_scheduledAt_key" ON "deadline_alerts"("deadlineId","scheduledAt");
CREATE INDEX "deadline_history_changedById_changedAt_idx" ON "deadline_history"("changedById","changedAt");
CREATE INDEX "deadline_history_correlationId_idx" ON "deadline_history"("correlationId");
CREATE UNIQUE INDEX "deadline_history_deadlineId_version_key" ON "deadline_history"("deadlineId","version");
ALTER TABLE "tender_deadlines" ADD CONSTRAINT "tender_deadlines_tenderId_fkey" FOREIGN KEY("tenderId") REFERENCES "tenders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "tender_deadlines" ADD CONSTRAINT "tender_deadlines_requirementId_fkey" FOREIGN KEY("requirementId") REFERENCES "tender_requirements"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "tender_deadlines" ADD CONSTRAINT "tender_deadlines_responsibleId_fkey" FOREIGN KEY("responsibleId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "tender_deadlines" ADD CONSTRAINT "tender_deadlines_confirmedById_fkey" FOREIGN KEY("confirmedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "deadline_alerts" ADD CONSTRAINT "deadline_alerts_deadlineId_fkey" FOREIGN KEY("deadlineId") REFERENCES "tender_deadlines"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "deadline_history" ADD CONSTRAINT "deadline_history_deadlineId_fkey" FOREIGN KEY("deadlineId") REFERENCES "tender_deadlines"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "deadline_history" ADD CONSTRAINT "deadline_history_changedById_fkey" FOREIGN KEY("changedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE OR REPLACE FUNCTION prevent_deadline_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'deadline_history is append-only'; END; $$;
CREATE TRIGGER deadline_history_append_only BEFORE UPDATE OR DELETE ON "deadline_history" FOR EACH ROW EXECUTE FUNCTION prevent_deadline_history_mutation();
CREATE OR REPLACE FUNCTION validate_deadline_alert_schedule() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE deadline_at TIMESTAMPTZ; BEGIN SELECT "dueAt" INTO STRICT deadline_at FROM "tender_deadlines" WHERE "id"=NEW."deadlineId"; IF NEW."scheduledAt">=deadline_at THEN RAISE EXCEPTION 'deadline alert must be scheduled before due date'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER deadline_alert_before_due BEFORE INSERT OR UPDATE ON "deadline_alerts" FOR EACH ROW EXECUTE FUNCTION validate_deadline_alert_schedule();
